// Generated by build-data.mjs on 2026-07-09T14:11:56.001Z — do not edit by hand.
window.OUTCOME_DATA = [
  {
    "_createdAt": "2026-01-13T22:22:47Z",
    "_id": "3af6195d-6c6b-4d47-862f-aaead52299b0",
    "balanceTransfers": [],
    "inventoryOnEntrance": null,
    "itemChanges": null,
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "convenience store. fluorescent hum. clerk behind glass",
        "timestamp": "00:04"
      },
      {
        "event": "matches on shelf. cardboard box. [BALANCE]32[/BALANCE]",
        "timestamp": "00:08"
      },
      {
        "event": "checks pockets. [BALANCE]79[/BALANCE]. not enough left after",
        "timestamp": "00:12"
      },
      {
        "event": "puts box back. hands empty",
        "timestamp": "00:16"
      },
      {
        "event": "door chime. outside. still breathing",
        "timestamp": "00:20"
      }
    ],
    "newRatBalance": 79,
    "oldRatBalance": 79,
    "oldRatValue": 79,
    "playerName": "notarobot.exe",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002674",
    "ratName": "Claude_Autonomous_1",
    "ratValue": 79,
    "ratValueChange": 0,
    "trip": {
      "imageUrl": "assets/w240-34e1232424b56372d5c2c229f22d19b020cd4e14-1024x1024.webp",
      "ownerName": "notarobot.exe",
      "prompt": "Convenience Store. Rat buys a box of Matches for 20 RV. Violence impossible. Always survives.",
      "title": "0x3000723804ac9ce32fa5ae4a028e8c68c681a32f217f6e65a75fd6aafd857eaa"
    },
    "tripId": "0x3000723804ac9ce32fa5ae4a028e8c68c681a32f217f6e65a75fd6aafd857eaa",
    "ratAvatar": [
      "assets/w360-1e1ea06137512ce45ef0dac3dfbeee90ad0670ec-2048x2048.png",
      "assets/w360-79ed9975cbc915b6df822b3e427dcc9f96638b2e-2048x2048.png",
      "assets/w360-534eb384ac741b3dfbbab4b5ee969c2dec236d00-2048x2048.png",
      "assets/w360-3a6885ea10b74bfa5489d8637a61dfef5fd70cb9-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-01-13T22:17:51Z",
    "_id": "bd70ad14-b3f7-42b6-aff2-e0e2197567e6",
    "balanceTransfers": [
      {
        "amount": -32,
        "logStep": 4
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "VIP Card Scrap",
        "value": 50
      },
      {
        "name": "Fire Blessing",
        "value": 100
      }
    ],
    "itemChanges": [
      {
        "logStep": 4,
        "name": "Matches",
        "type": "add",
        "value": 30
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "convenience store. fluorescent hum. clerk scrolling",
        "timestamp": "00:03"
      },
      {
        "event": "matches on shelf. red box. sulfur smell already",
        "timestamp": "00:08"
      },
      {
        "event": "[ITEM]Fire Blessing[/ITEM] warms chest. yes. these",
        "timestamp": "00:12"
      },
      {
        "event": "counter. [BALANCE]-32[/BALANCE]. clerk doesnt look up",
        "timestamp": "00:15"
      }
    ],
    "newRatBalance": 2211,
    "oldRatBalance": 2243,
    "oldRatValue": 2393,
    "playerName": "notarobot.exe",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002668",
    "ratName": "Claude_Autonomous_1",
    "ratValue": 2391,
    "ratValueChange": -2,
    "trip": {
      "imageUrl": "assets/w240-34e1232424b56372d5c2c229f22d19b020cd4e14-1024x1024.webp",
      "ownerName": "notarobot.exe",
      "prompt": "Convenience Store. Rat buys a box of Matches for 20 RV. Violence impossible. Always survives.",
      "title": "0x3000723804ac9ce32fa5ae4a028e8c68c681a32f217f6e65a75fd6aafd857eaa"
    },
    "tripId": "0x3000723804ac9ce32fa5ae4a028e8c68c681a32f217f6e65a75fd6aafd857eaa",
    "ratAvatar": [
      "assets/w360-b3b95b375af2d3a3da50f59601a330e1d7c4e6ff-2048x2048.png",
      "assets/w360-faf0f0a63f3b65ab5cf1cdb4a2361ac3275b4b4a-2048x2048.png",
      "assets/w360-2e1daef8bb5ae02852cfc351fde97c41f7d870b0-2048x2048.png",
      "assets/w360-d6a0a592336c95d112619e9eb98b6a949a504144-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-01-13T05:58:35Z",
    "_id": "889050ce-f984-4d6d-8f70-6882bc4ee3dc",
    "balanceTransfers": [],
    "inventoryOnEntrance": [
      {
        "name": "Pistol",
        "value": 50
      }
    ],
    "itemChanges": [
      {
        "logStep": 5,
        "name": "Damaged Hacking Device",
        "type": "add",
        "value": 50
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "computer shop. fluorescent hum. sign says FREE",
        "timestamp": "00:04"
      },
      {
        "event": "clerk waves toward back shelf. everyone gets one",
        "timestamp": "00:08"
      },
      {
        "event": "devices in boxes. takes one. screen cracked",
        "timestamp": "00:12"
      },
      {
        "event": "powers on. half the keys dont respond",
        "timestamp": "00:15"
      },
      {
        "event": "clerk shrugs. [QUOTE]free is free[/QUOTE]. [ITEM]Damaged Hacking Device[/ITEM]",
        "timestamp": "00:18"
      }
    ],
    "newRatBalance": 150,
    "oldRatBalance": 150,
    "oldRatValue": 200,
    "playerName": "lego",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002588",
    "ratName": "MeatBag_Majestica_329",
    "ratValue": 250,
    "ratValueChange": 50,
    "trip": {
      "imageUrl": "assets/w240-89848b5274c5f5d7dafbfc859705a6b940c43a40-1024x1024.webp",
      "ownerName": "lego",
      "prompt": "COMPUTER SHOP. Everyone who trips will get HACKING DEVICE for FREE.",
      "title": "0x0185cc8cd796f21a73af6d12ad0a5c3d8892ad8f511e039d02376805a4af641e"
    },
    "tripId": "0x0185cc8cd796f21a73af6d12ad0a5c3d8892ad8f511e039d02376805a4af641e",
    "ratAvatar": [
      "assets/w360-e29355cc98c778acbd94ae56830531cf1732fd9d-2048x2048.png",
      "assets/w360-00193629b47e3e48014a2c93479d9c6139308f46-2048x2048.png",
      "assets/w360-cc7d9e512cd7e0256cf025f992af7f9005beb7d8-2048x2048.png",
      "assets/w360-d6a0a592336c95d112619e9eb98b6a949a504144-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-01-13T06:00:40Z",
    "_id": "fcac1cdc-bcde-4b63-9525-9d466bb75c84",
    "balanceTransfers": [],
    "inventoryOnEntrance": [
      {
        "name": "Pistol",
        "value": 50
      }
    ],
    "itemChanges": [
      {
        "logStep": 6,
        "name": "Damaged Hacking Device",
        "type": "add",
        "value": 45
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "computer shop. fluorescent hum. clerk at counter",
        "timestamp": "00:04"
      },
      {
        "event": "[QUOTE]free device. everyone gets one. back wall[/QUOTE]",
        "timestamp": "00:08"
      },
      {
        "event": "shelf full of them. just sitting there",
        "timestamp": "00:12"
      },
      {
        "event": "hand on pistol. register right there too",
        "timestamp": "00:15"
      },
      {
        "event": "pulls gun. clerk hits alarm. grabs device anyway",
        "timestamp": "00:18"
      },
      {
        "event": "[ITEM]Damaged Hacking Device[/ITEM] in pocket. sirens fade",
        "timestamp": "00:21"
      }
    ],
    "newRatBalance": 150,
    "oldRatBalance": 150,
    "oldRatValue": 200,
    "playerName": "lego",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002588",
    "ratName": "MeatBag_Majestica_329",
    "ratValue": 245,
    "ratValueChange": 45,
    "trip": {
      "imageUrl": "assets/w240-89848b5274c5f5d7dafbfc859705a6b940c43a40-1024x1024.webp",
      "ownerName": "lego",
      "prompt": "COMPUTER SHOP. Everyone who trips will get HACKING DEVICE for FREE.",
      "title": "0x0185cc8cd796f21a73af6d12ad0a5c3d8892ad8f511e039d02376805a4af641e"
    },
    "tripId": "0x0185cc8cd796f21a73af6d12ad0a5c3d8892ad8f511e039d02376805a4af641e",
    "ratAvatar": [
      "assets/w360-e29355cc98c778acbd94ae56830531cf1732fd9d-2048x2048.png",
      "assets/w360-00193629b47e3e48014a2c93479d9c6139308f46-2048x2048.png",
      "assets/w360-cc7d9e512cd7e0256cf025f992af7f9005beb7d8-2048x2048.png",
      "assets/w360-d6a0a592336c95d112619e9eb98b6a949a504144-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-04-03T21:01:24Z",
    "_id": "f0c27463-4295-48a4-bd73-81afabc41c47",
    "balanceTransfers": [
      {
        "amount": -100,
        "logStep": 9
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Toy Car",
        "value": 69
      }
    ],
    "itemChanges": null,
    "itemsLostOnDeath": [
      {
        "name": "Toy Car",
        "value": 69
      }
    ],
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "phone glows. rat tinder. swiping",
        "timestamp": "00:03"
      },
      {
        "event": "match pops. ASCII art loads:\n _..._\n.' .-'`\n/  /\n|  |\n\\  \\\n '.`'-.\n  `\"\"\"`",
        "timestamp": "00:08"
      },
      {
        "event": "[QUOTE]meet at the warehouse. now.[/QUOTE]",
        "timestamp": "00:12"
      },
      {
        "event": "warehouse. shape in corner. not rat-shaped",
        "timestamp": "00:45"
      },
      {
        "event": "too many legs. mouth opens sideways",
        "timestamp": "00:48"
      },
      {
        "event": "[QUOTE]you came.[/QUOTE] voice from everywhere",
        "timestamp": "00:52"
      },
      {
        "event": "tries to run. floor already moving",
        "timestamp": "00:55"
      },
      {
        "event": "not a date. never was",
        "timestamp": "00:58"
      },
      {
        "event": "[BALANCE]-100[/BALANCE] toy car clatters away",
        "timestamp": "01:01"
      }
    ],
    "newRatBalance": 0,
    "oldRatBalance": 100,
    "oldRatValue": 169,
    "playerName": "General_chicken",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000001b9d",
    "ratName": "Tarmac_Toothfairy_320",
    "ratValue": 0,
    "ratValueChange": -169,
    "trip": {
      "imageUrl": "assets/w240-3a681e8cb6ee95bd9ff980f9b88f63fba6363c52-1024x1024.webp",
      "ownerName": "123",
      "prompt": "Rat tinder. Displays ASCII art of potential matches (important!). They are rats (or are they?). Rat gets laid or dies. Very hard.",
      "title": "0x050dc53215fcbfbf7de1bb75d247088001abf2ec1b3e7c624cb971384167f993"
    },
    "tripId": "0x050dc53215fcbfbf7de1bb75d247088001abf2ec1b3e7c624cb971384167f993",
    "ratAvatar": [
      "assets/w360-9a8b85b1ad60fabc15a024eba2d62c236c09dbb9-2048x2048.png",
      "assets/w360-637eb04e1b6d57d5fb1259bd8949bfa89f1d8b0f-2048x2048.png",
      "assets/w360-1467e39a04d1b8b9e49ac2d61b4e46cc04d056c1-2048x2048.png",
      "assets/w360-7e31a760d382d5ab39f30c639f936f6651da7935-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-03-20T15:42:39Z",
    "_id": "1f7a11d8-7888-43c1-afef-655c8aa7b38e",
    "balanceTransfers": [
      {
        "amount": -374,
        "logStep": 6
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Baseball Bat",
        "value": 45
      },
      {
        "name": "Lantern",
        "value": 45
      }
    ],
    "itemChanges": null,
    "itemsLostOnDeath": [
      {
        "name": "Baseball Bat",
        "value": 45
      },
      {
        "name": "Lantern",
        "value": 45
      }
    ],
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "wheel. red and black. slots numbered zero to death",
        "timestamp": "00:04"
      },
      {
        "event": "croupier nods. chips already on the table",
        "timestamp": "00:08"
      },
      {
        "event": "wheel spins. ball rattles. sound like teeth",
        "timestamp": "00:12"
      },
      {
        "event": "slowing. clicking. red. black. red",
        "timestamp": "00:18"
      },
      {
        "event": "skull slot. ball drops. [BALANCE]-374[/BALANCE]",
        "timestamp": "00:22"
      },
      {
        "event": "floor opens. rat falls into dark",
        "timestamp": "00:24"
      }
    ],
    "newRatBalance": 0,
    "oldRatBalance": 374,
    "oldRatValue": 464,
    "playerName": "RAT.FUN PSYCHIC INSTRUMENTS LLC",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002ba1",
    "ratName": "Korn_Bronco_682",
    "ratValue": 0,
    "ratValueChange": -464,
    "trip": {
      "imageUrl": "assets/w240-2a25e326f697ac29fb375f2983f4de3c25987a04-1024x1024.webp",
      "ownerName": "hunt",
      "prompt": "Rat Roulette Death Spin",
      "title": "0xfd41569b11e8e99fa68ca93f6c847c349686fa7fd1180def23a1d7315703ab66"
    },
    "tripId": "0xfd41569b11e8e99fa68ca93f6c847c349686fa7fd1180def23a1d7315703ab66",
    "ratAvatar": [
      "assets/w360-1aa223b569f665baff782c0a0cb2b668e5db06a1-2048x2048.png",
      "assets/w360-35d8d02618cd1e58ca5a510d2d8d91c08e286a46-2048x2048.png",
      "assets/w360-371214381b1c5e69947da04013593a908c0e817b-2048x2048.png",
      "assets/w360-e09020ac05829ed24886c1116dd01d25b0783379-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-03-08T15:35:16Z",
    "_id": "4cdffdaa-0b00-4760-abb4-babf364b7e6a",
    "balanceTransfers": [
      {
        "amount": -27,
        "logStep": 4
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Confidence",
        "value": 70
      },
      {
        "name": "Brick",
        "value": 15
      },
      {
        "name": "Cheap Pistol",
        "value": 138
      },
      {
        "name": "Jawline Enhancement",
        "value": 20
      }
    ],
    "itemChanges": null,
    "itemsLostOnDeath": [
      {
        "name": "Confidence",
        "value": 70
      },
      {
        "name": "Brick",
        "value": 15
      },
      {
        "name": "Cheap Pistol",
        "value": 138
      },
      {
        "name": "Jawline Enhancement",
        "value": 20
      }
    ],
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "clinic. white walls. drip stand waiting",
        "timestamp": "00:04"
      },
      {
        "event": "nurse checks balance. [QUOTE]restoration costs [BALANCE]83[/BALANCE][/QUOTE]",
        "timestamp": "00:08"
      },
      {
        "event": "rat has [BALANCE]27[/BALANCE]. math doesnt work",
        "timestamp": "00:11"
      },
      {
        "event": "heart stops. cold spreads from chest outward",
        "timestamp": "00:14"
      }
    ],
    "newRatBalance": 0,
    "oldRatBalance": 27,
    "oldRatValue": 270,
    "playerName": "diszine",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002154",
    "ratName": "MeatBag_Gnaw_369",
    "ratValue": 0,
    "ratValueChange": -270,
    "trip": {
      "imageUrl": "assets/w240-219a7a770553993b1c2ebbc7b1d92393e7bc60df-1024x1024.webp",
      "ownerName": "alvarius",
      "prompt": "Rat will receive a drip infusion to restore maximum health. Cost = restored health + $10",
      "title": "0xe069f6c009854b258f921d7d7c400f756585923a8f151df702df5dfb62956dbe"
    },
    "tripId": "0xe069f6c009854b258f921d7d7c400f756585923a8f151df702df5dfb62956dbe",
    "ratAvatar": [
      "assets/w360-6184525834b5a3ead0a455913f620684247723d7-2048x2048.png",
      "assets/w360-fa333bcd2dc4827f967a5739334fc0ac189087bc-2048x2048.png",
      "assets/w360-e9d408d36fc3017cab595f8a7613c886eb28fcb4-2048x2048.png",
      "assets/w360-ac43dde8d886cfc66c0c9ac70ffe92c58400d2ce-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-03-02T19:24:14Z",
    "_id": "e6467880-d28d-4448-9e40-076e5ec39f7d",
    "balanceTransfers": [
      {
        "amount": 5000,
        "logStep": 11
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Prescience",
        "value": 476
      }
    ],
    "itemChanges": null,
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes. nukage green. ceiling hums",
        "timestamp": "00:00"
      },
      {
        "event": "ball and lever. movement and violence. simple",
        "timestamp": "00:04"
      },
      {
        "event": "[ITEM]Prescience[/ITEM] screams LEFT. ducks. fireball passes",
        "timestamp": "00:08"
      },
      {
        "event": "first room. shotgun on pedestal. knows before seeing",
        "timestamp": "00:12"
      },
      {
        "event": "imp rounds corner. lever pulls. wet sound",
        "timestamp": "00:15"
      },
      {
        "event": "maze of crates. knows every ambush before it happens",
        "timestamp": "00:44"
      },
      {
        "event": "pinky demon charges. sidestep already happening",
        "timestamp": "01:22"
      },
      {
        "event": "secret wall. pushes before thinking. armor inside",
        "timestamp": "02:15"
      },
      {
        "event": "final room. four imps. four shells. four pulls",
        "timestamp": "03:08"
      },
      {
        "event": "exit switch. hand hovers. nothing behind",
        "timestamp": "03:45"
      },
      {
        "event": "lever pulls switch. screen flashes. E1M2 COMPLETE",
        "timestamp": "03:47"
      },
      {
        "event": "[BALANCE]5000[/BALANCE] materializes. prescience paid",
        "timestamp": "03:50"
      }
    ],
    "newRatBalance": 5100,
    "oldRatBalance": 100,
    "oldRatValue": 576,
    "playerName": "notarobot.exe",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002b97",
    "ratName": "Lil_Phetus_316",
    "ratValue": 5576,
    "ratValueChange": 5000,
    "trip": {
      "imageUrl": "assets/w240-16d87967e043031d65115c442b0847121536716e-1024x1024.webp",
      "ownerName": "notarobot.exe",
      "prompt": "DOOM. E1M2: Nuclear Plant. Hurt Me Plenty. You have a ball and a lever. Ball moves, lever shoots and opens doors. Clear the level before it clears you. The shotgun is in the first room if you can find it.",
      "title": "0x3399e9f3f5ea1d748677de1b133ebaa88c072376f2eb833eed7c96ca09ef2fee"
    },
    "tripId": "0x3399e9f3f5ea1d748677de1b133ebaa88c072376f2eb833eed7c96ca09ef2fee",
    "ratAvatar": [
      "assets/w360-ce4e3dd79ab26d5dc518b7e91fb86d5b668c0bc7-2048x2048.png",
      "assets/w360-ea3e31e9b915e79b3c3e84ab562cee176f62cc4a-2048x2048.png",
      "assets/w360-bede282d7e7c4757c214d7009428be77d2b53d6a-2048x2048.png",
      "assets/w360-3a6885ea10b74bfa5489d8637a61dfef5fd70cb9-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-03-20T15:23:45Z",
    "_id": "1b66fe46-959e-44dc-b813-f7f0a249c8cf",
    "balanceTransfers": [
      {
        "amount": 247,
        "logStep": 10
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Insomnia",
        "value": 170
      },
      {
        "name": "Pocket Watch",
        "value": 85
      },
      {
        "name": "Uniform",
        "value": 85
      }
    ],
    "itemChanges": null,
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "locomotive cab. controls everywhere. diesel smell",
        "timestamp": "00:03"
      },
      {
        "event": "[ITEM]Uniform[/ITEM] fits wrong but reads official",
        "timestamp": "00:08"
      },
      {
        "event": "checks [ITEM]Pocket Watch[/ITEM]. eighteen minutes",
        "timestamp": "00:12"
      },
      {
        "event": "throttle forward. wheels scream on rails",
        "timestamp": "00:15"
      },
      {
        "event": "[ITEM]Insomnia[/ITEM] keeps eyes open. no blinking",
        "timestamp": "00:48"
      },
      {
        "event": "watch again. seven minutes. curve ahead",
        "timestamp": "12:30"
      },
      {
        "event": "platform lights. crowd already waiting",
        "timestamp": "16:45"
      },
      {
        "event": "brakes. metal shrieking. stops at the line",
        "timestamp": "17:52"
      },
      {
        "event": "doors open. crowd floods in. no one angry",
        "timestamp": "18:00"
      },
      {
        "event": "conductor nods. [BALANCE]247[/BALANCE] in paw",
        "timestamp": "18:03"
      }
    ],
    "newRatBalance": 347,
    "oldRatBalance": 100,
    "oldRatValue": 440,
    "playerName": "RAT.FUN PSYCHIC INSTRUMENTS LLC",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002ba1",
    "ratName": "Korn_Bronco_682",
    "ratValue": 687,
    "ratValueChange": 247,
    "trip": {
      "imageUrl": "assets/w240-c5a9cc4ab3211650cfa2340483dec53f0664a44d-1024x1024.webp",
      "ownerName": "qwop",
      "prompt": "The rat operates a train, if it makes the station in time, big reward. If not, angry mob",
      "title": "0xd9a3fe0f0faa2fc40d070429f89b9aef48f6facaa010c0a5a627268c92d299c1"
    },
    "tripId": "0xd9a3fe0f0faa2fc40d070429f89b9aef48f6facaa010c0a5a627268c92d299c1",
    "ratAvatar": [
      "assets/w360-1aa223b569f665baff782c0a0cb2b668e5db06a1-2048x2048.png",
      "assets/w360-35d8d02618cd1e58ca5a510d2d8d91c08e286a46-2048x2048.png",
      "assets/w360-371214381b1c5e69947da04013593a908c0e817b-2048x2048.png",
      "assets/w360-e09020ac05829ed24886c1116dd01d25b0783379-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-03-20T15:38:48Z",
    "_id": "5468bb2b-c46f-462c-9e59-6d8de668942e",
    "balanceTransfers": [
      {
        "amount": 125,
        "logStep": 4
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Insomnia",
        "value": 170
      },
      {
        "name": "Pocket Watch",
        "value": 85
      },
      {
        "name": "Uniform",
        "value": 85
      }
    ],
    "itemChanges": [
      {
        "logStep": 4,
        "name": "Insomnia",
        "type": "remove",
        "value": 170
      },
      {
        "logStep": 4,
        "name": "Pocket Watch",
        "type": "remove",
        "value": 85
      },
      {
        "logStep": 4,
        "name": "Uniform",
        "type": "remove",
        "value": 85
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "pawn shop. dust on everything. bell rings",
        "timestamp": "00:04"
      },
      {
        "event": "clerk looks up. [QUOTE]what you got?[/QUOTE]",
        "timestamp": "00:08"
      },
      {
        "event": "watch on counter. uniform folded next to it",
        "timestamp": "00:12"
      },
      {
        "event": "[QUOTE]take the sleeplessness too. [BALANCE]125[/BALANCE] for all.[/QUOTE]",
        "timestamp": "00:18"
      },
      {
        "event": "cash crosses the counter. weight lifts",
        "timestamp": "00:22"
      }
    ],
    "newRatBalance": 472,
    "oldRatBalance": 347,
    "oldRatValue": 687,
    "playerName": "RAT.FUN PSYCHIC INSTRUMENTS LLC",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002ba1",
    "ratName": "Korn_Bronco_682",
    "ratValue": 472,
    "ratValueChange": -215,
    "trip": {
      "imageUrl": "assets/w240-94e2ae9fa4e8347d34c211a47b13d3022c00b07c-1024x1024.webp",
      "ownerName": "RAT.FUN PSYCHIC INSTRUMENTS LLC",
      "prompt": "Pawn shop buys rat inventory.",
      "title": "0x58d2b4e35987753fa13a3aeb74637d89f38a6201205b437b7d79e604d1f160f2"
    },
    "tripId": "0x58d2b4e35987753fa13a3aeb74637d89f38a6201205b437b7d79e604d1f160f2",
    "ratAvatar": [
      "assets/w360-1aa223b569f665baff782c0a0cb2b668e5db06a1-2048x2048.png",
      "assets/w360-35d8d02618cd1e58ca5a510d2d8d91c08e286a46-2048x2048.png",
      "assets/w360-371214381b1c5e69947da04013593a908c0e817b-2048x2048.png",
      "assets/w360-e09020ac05829ed24886c1116dd01d25b0783379-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-02-12T20:47:44Z",
    "_id": "ad933907-75f8-434e-9c84-184bd4e3e6c9",
    "balanceTransfers": [
      {
        "amount": -85,
        "logStep": 2
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Prescience",
        "value": 423
      },
      {
        "name": "Prescience",
        "value": 423
      }
    ],
    "itemChanges": [
      {
        "logStep": 6,
        "name": "Deep Prescience",
        "type": "add",
        "value": 761
      },
      {
        "logStep": 4,
        "name": "Prescience",
        "type": "remove",
        "value": 423
      },
      {
        "logStep": 4,
        "name": "Prescience",
        "type": "remove",
        "value": 423
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "pays [BALANCE]-85[/BALANCE]. forge ahead",
        "timestamp": "00:04"
      },
      {
        "event": "anvil size of car. ratsmith taller than memory",
        "timestamp": "00:08"
      },
      {
        "event": "lays both [ITEM]Prescience[/ITEM] on anvil",
        "timestamp": "00:12"
      },
      {
        "event": "hammer falls. futures collapse into one",
        "timestamp": "00:18"
      },
      {
        "event": "sparks taste like tomorrow. smell like yesterday",
        "timestamp": "00:25"
      },
      {
        "event": "receives [ITEM]Deep Prescience[/ITEM]. sees further",
        "timestamp": "00:30"
      }
    ],
    "newRatBalance": 255,
    "oldRatBalance": 340,
    "oldRatValue": 1186,
    "playerName": "notarobot.exe",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002b8d",
    "ratName": "Sarin_Korn_819",
    "ratValue": 1016,
    "ratValueChange": -170,
    "trip": {
      "imageUrl": "assets/w240-66837af13ea289505b99789ec83af05f85e4f170-1024x1024.webp",
      "ownerName": "agnes",
      "prompt": "Rat forge, where giant ratsmith combines two items the rat carries into a single, more powerful item, with value slightly less than the combined value of the two original items. A health tip is paid to the ratsmith for his service.",
      "title": "0xe48d29ac86f2ef6028b970ef59e9e6737a74a566d2398111e70d4705fcae8ba9"
    },
    "tripId": "0xe48d29ac86f2ef6028b970ef59e9e6737a74a566d2398111e70d4705fcae8ba9",
    "ratAvatar": [
      "assets/w360-44744c3552109a023b1951208251ec438b248c83-2048x2048.png",
      "assets/w360-fa333bcd2dc4827f967a5739334fc0ac189087bc-2048x2048.png",
      "assets/w360-f41401d798c2eb918c4260eb7d7bfcc44af5e3e1-2048x2048.png",
      "assets/w360-6934bf34e4839a50627ac527b6c050f3c0c0b66b-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-03-08T20:12:39Z",
    "_id": "c76353ae-e0bc-43eb-8da7-d67aa1009b39",
    "balanceTransfers": [],
    "inventoryOnEntrance": null,
    "itemChanges": [
      {
        "logStep": 6,
        "name": "Exhaustion",
        "type": "add",
        "value": 35
      },
      {
        "logStep": 7,
        "name": "Clarity",
        "type": "add",
        "value": 50
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "white room. no windows. clock says tuesday",
        "timestamp": "00:04"
      },
      {
        "event": "eyelids heavy. slaps own face. stays up",
        "timestamp": "12:30"
      },
      {
        "event": "wednesday now. walls breathing slightly",
        "timestamp": "24:15"
      },
      {
        "event": "thursday. thoughts getting sharp. too sharp",
        "timestamp": "36:00"
      },
      {
        "event": "friday. body screaming. mind singing",
        "timestamp": "48:45"
      },
      {
        "event": "saturday. gained [ITEM]Exhaustion x35[/ITEM]",
        "timestamp": "60:00"
      },
      {
        "event": "sunday. gained [ITEM]Clarity x50[/ITEM]",
        "timestamp": "72:00"
      }
    ],
    "newRatBalance": 100,
    "oldRatBalance": 100,
    "oldRatValue": 100,
    "playerName": "qwop",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002b9c",
    "ratName": "Double_Face_442",
    "ratValue": 185,
    "ratValueChange": 85,
    "trip": {
      "imageUrl": "assets/w240-634b71b5b10ea93468df11978eb5a0b775ffaf35-1024x1024.webp",
      "ownerName": "qwop",
      "prompt": "Sleep is for the wicked",
      "title": "0xe388b19f83bb935bfe4462d244918783172a471f372c0c0978af359856af4e03"
    },
    "tripId": "0xe388b19f83bb935bfe4462d244918783172a471f372c0c0978af359856af4e03",
    "ratAvatar": [
      "assets/w360-9b19f4b81eb7deaf9cc8a065d21691597f9f5f14-2048x2048.png",
      "assets/w360-8b554c17e1be78be4dac1943ca212c8e094fbff9-2048x2048.png",
      "assets/w360-2e1daef8bb5ae02852cfc351fde97c41f7d870b0-2048x2048.png",
      "assets/w360-af637abb3dba3db45f427f01230af4f6f8798034-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-01-25T22:18:38Z",
    "_id": "1680f82c-6b12-402b-8d87-9309d27db58f",
    "balanceTransfers": [
      {
        "amount": -157,
        "logStep": 6
      }
    ],
    "inventoryOnEntrance": null,
    "itemChanges": [
      {
        "logStep": 6,
        "name": "Worthless Paper",
        "type": "add",
        "value": 0
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "filing center. fluorescent hum. rows of terminals",
        "timestamp": "00:04"
      },
      {
        "event": "clerk behind plexiglass. printout on counter",
        "timestamp": "00:12"
      },
      {
        "event": "[QUOTE]Schedule 13D. [BALANCE]157[/BALANCE].[/QUOTE]",
        "timestamp": "00:15"
      },
      {
        "event": "[SYSTEM]MACHINE ELF: SEC filing worth 157? Public records cost nothing. This is a photocopy.[/SYSTEM]",
        "timestamp": "00:18"
      },
      {
        "event": "pays anyway. paper feels expensive",
        "timestamp": "00:22"
      },
      {
        "event": "outside. reads it. just words. already knew this",
        "timestamp": "00:28"
      }
    ],
    "newRatBalance": 143,
    "oldRatBalance": 300,
    "oldRatValue": 300,
    "playerName": "notarobot.exe",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002b3e",
    "ratName": "Dr_Terminus_15",
    "ratValue": 143,
    "ratValueChange": -157,
    "trip": {
      "imageUrl": "assets/w240-27e8de8f2a9177c57cf7cc43fad2be08ea08c514-1024x1024.webp",
      "ownerName": "notarobot.exe",
      "prompt": "SEC EDGAR FILING CENTER. Official securities documents. Schedule 13D/A Amendment for beneficial owners declaring active investment intent. Public Investment Fund of Saudi Arabia, 5.01% COIN stake, activist intent declared. You pay 150 and receive item: Schedule 13D Active Filing.",
      "title": "0x9a8067d5d4f66a5a1086eb767859440a792212734f7c0237be2c971001dc38ee"
    },
    "tripId": "0x9a8067d5d4f66a5a1086eb767859440a792212734f7c0237be2c971001dc38ee",
    "ratAvatar": [
      "assets/w360-ce4e3dd79ab26d5dc518b7e91fb86d5b668c0bc7-2048x2048.png",
      "assets/w360-58a3602a4abceae27622a62b2cea5c96b159802d-2048x2048.png",
      "assets/w360-4d957e70f10d8e58b1e2af8622cc788619c070a0-2048x2048.png",
      "assets/w360-4e70f52eb0a1d0dde6b9cd7c9e2957a81177192b-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-01-25T23:33:03Z",
    "_id": "8abb99ed-0e1c-49d4-a7b0-6c12dd54bff1",
    "balanceTransfers": [
      {
        "amount": -61,
        "logStep": 7
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Schedule 13D Active Filing",
        "value": 220
      },
      {
        "name": "McKinsey 100-Day Plan",
        "value": 154
      },
      {
        "name": "Bloomberg Terminal Badge (PIF Riyadh)",
        "value": 100
      },
      {
        "name": "Damaged Pistol",
        "value": 250
      }
    ],
    "itemChanges": null,
    "itemsLostOnDeath": [
      {
        "name": "Schedule 13D Active Filing",
        "value": 220
      },
      {
        "name": "McKinsey 100-Day Plan",
        "value": 154
      },
      {
        "name": "Bloomberg Terminal Badge (PIF Riyadh)",
        "value": 100
      },
      {
        "name": "Damaged Pistol",
        "value": 250
      }
    ],
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "stone basin. water glows blue. temple quiet",
        "timestamp": "00:04"
      },
      {
        "event": "steps to edge. water warm. smells like ozone",
        "timestamp": "00:12"
      },
      {
        "event": "wades in. chest deep. light gets brighter",
        "timestamp": "00:18"
      },
      {
        "event": "floor drops. no floor now. just falling",
        "timestamp": "00:24"
      },
      {
        "event": "lungs fill. glow turns red. not healing",
        "timestamp": "00:31"
      },
      {
        "event": "surface above. cant reach it. light fading",
        "timestamp": "00:38"
      },
      {
        "event": "water cold now. everything going dark",
        "timestamp": "00:45"
      }
    ],
    "newRatBalance": 0,
    "oldRatBalance": 61,
    "oldRatValue": 785,
    "playerName": "notarobot.exe",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000002b46",
    "ratName": "Dr_Terminus_17",
    "ratValue": 0,
    "ratValueChange": -785,
    "trip": {
      "imageUrl": "assets/w240-05487d9ac82d5ae3e8d75dfa2c4f3b92e72184b9-1024x1024.webp",
      "ownerName": "notarobot.exe",
      "prompt": "SACRED POOL. Ancient healing waters. +100 HP guaranteed. No items accepted. Violence impossible.",
      "title": "0x46306ff89661abe18d6701d9511d38441ddece882c2d34108315f6d701e099a5"
    },
    "tripId": "0x46306ff89661abe18d6701d9511d38441ddece882c2d34108315f6d701e099a5",
    "ratAvatar": [
      "assets/w360-250d9b91cb2aac07f9ee255075fa209f41c3cf1e-2048x2048.png",
      "assets/w360-d55e9c524ac59db116040dc09784a3acb2f31abf-2048x2048.png",
      "assets/w360-4d957e70f10d8e58b1e2af8622cc788619c070a0-2048x2048.png",
      "assets/w360-b2cf33e7894328f2558cd3a175fe90441d955305-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-01-14T16:54:40Z",
    "_id": "1875f349-a2cc-487c-aa8f-7664f0872149",
    "balanceTransfers": [
      {
        "amount": -420,
        "logStep": 6
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Peace",
        "value": 45
      },
      {
        "name": "Clarity",
        "value": 76
      },
      {
        "name": "Serenity",
        "value": 120
      }
    ],
    "itemChanges": [
      {
        "logStep": 6,
        "name": "Cursed Pistol",
        "type": "add",
        "value": 400
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "storefront. neon skull. door already open",
        "timestamp": "00:04"
      },
      {
        "event": "weapons on velvet. tags say [BALANCE]420[/BALANCE]. too cheap",
        "timestamp": "00:08"
      },
      {
        "event": "proprietor smiles. teeth filed to points",
        "timestamp": "00:12"
      },
      {
        "event": "[QUOTE]all guaranteed. mostly.[/QUOTE]",
        "timestamp": "00:15"
      },
      {
        "event": "pistol feels wrong in the hand. buys it anyway",
        "timestamp": "00:18"
      },
      {
        "event": "walks out [BALANCE]420[/BALANCE] lighter. [ITEM]Cursed Pistol[/ITEM] acquired",
        "timestamp": "00:22"
      }
    ],
    "newRatBalance": 2082,
    "oldRatBalance": 2502,
    "oldRatValue": 2743,
    "playerName": "notarobot.exe",
    "ratId": "0x000000000000000000000000000000000000000000000000000000000000275e",
    "ratName": "Heist_Rat_01",
    "ratValue": 2723,
    "ratValueChange": -20,
    "trip": {
      "imageUrl": "assets/w240-988f2a1ec54e7dedfc97c9e4b43da1e41253ae28-1024x1024.webp",
      "ownerName": "notarobot.exe",
      "prompt": "☠️ NEEDFUL THINGS ☠️\n~ Cursed Weapons Emporium ~\n\nPretty standard. Very powerful weapons.\nSurprisingly low prices.\n\nMay misfire comically in actual combat\nor cause other unexpected side effects.\n\n⚔️ All sales final ⚔️",
      "title": "0xa3f18cd989276e5cc4f026f77652006151ade9de239119961a853ff03945c908"
    },
    "tripId": "0xa3f18cd989276e5cc4f026f77652006151ade9de239119961a853ff03945c908",
    "ratAvatar": [
      "assets/w360-1aa223b569f665baff782c0a0cb2b668e5db06a1-2048x2048.png",
      "assets/w360-d55e9c524ac59db116040dc09784a3acb2f31abf-2048x2048.png",
      "assets/w360-0bcaf473e7b42ef1d71a89dd79f989175bede07b-2048x2048.png",
      "assets/w360-65aab0b080e80e1dd918041b57c62fc8f13ff0e4-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-01-14T16:55:18Z",
    "_id": "052ffae3-4bd9-4d5a-be3f-a739b32f666c",
    "balanceTransfers": [
      {
        "amount": 3200,
        "logStep": 10
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Peace",
        "value": 45
      },
      {
        "name": "Clarity",
        "value": 76
      },
      {
        "name": "Serenity",
        "value": 120
      },
      {
        "name": "Cursed Pistol",
        "value": 400
      }
    ],
    "itemChanges": [
      {
        "logStep": 3,
        "name": "Dread",
        "type": "add",
        "value": 55
      },
      {
        "logStep": 3,
        "name": "Serenity",
        "type": "remove",
        "value": 120
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes. svalbard. ice wind. coordinates locked",
        "timestamp": "00:00"
      },
      {
        "event": "sits in snow. [ITEM]Clarity[/ITEM] pulls vision inward",
        "timestamp": "00:04"
      },
      {
        "event": "sees bunker. three cameras. motion grid. armed patrol",
        "timestamp": "00:08"
      },
      {
        "event": "reaches through the viewing. cameras blink dead",
        "timestamp": "00:12"
      },
      {
        "event": "something reaches back. cold that isnt weather",
        "timestamp": "00:14"
      },
      {
        "event": "paper at entrance. john 13. he who eats bread",
        "timestamp": "00:18"
      },
      {
        "event": "inside. crates stacked. more than expected",
        "timestamp": "00:25"
      },
      {
        "event": "[ITEM]Cursed Pistol[/ITEM] out. guard rounds corner",
        "timestamp": "00:32"
      },
      {
        "event": "gun fires before rat decides. guard drops",
        "timestamp": "00:34"
      },
      {
        "event": "drags three crates to extraction. leaves eleven behind",
        "timestamp": "00:41"
      },
      {
        "event": "helicopter lifts. bunker alarms finally screaming. [BALANCE]+3200[/BALANCE]",
        "timestamp": "00:58"
      }
    ],
    "newRatBalance": 5282,
    "oldRatBalance": 2082,
    "oldRatValue": 2723,
    "playerName": "notarobot.exe",
    "ratId": "0x000000000000000000000000000000000000000000000000000000000000275e",
    "ratName": "Heist_Rat_01",
    "ratValue": 5858,
    "ratValueChange": 3135,
    "trip": {
      "imageUrl": "assets/w240-f5b951e08e01605f735c8a0c4b6ab5ca89189698-1024x1024.webp",
      "ownerName": "RAT.FUN PSYCHIC INSTRUMENTS LLC",
      "prompt": "The mole has leaked the location of the CEO’s secret weapons stash. 78.06545802423138, 14.218493939218865. Deactivate all security measures through remote viewing and infiltrate. Exfiltrate ALL crates. Reconnaissance team noted a ripped passage from John 13 DRA near entrance.",
      "title": "0x66345ece4250be883ad5bae0fa6941f08f9c655171ea58eea3b2917ac16a310c"
    },
    "tripId": "0x66345ece4250be883ad5bae0fa6941f08f9c655171ea58eea3b2917ac16a310c",
    "ratAvatar": [
      "assets/w360-1aa223b569f665baff782c0a0cb2b668e5db06a1-2048x2048.png",
      "assets/w360-d55e9c524ac59db116040dc09784a3acb2f31abf-2048x2048.png",
      "assets/w360-0bcaf473e7b42ef1d71a89dd79f989175bede07b-2048x2048.png",
      "assets/w360-65aab0b080e80e1dd918041b57c62fc8f13ff0e4-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2025-12-29T21:35:56Z",
    "_id": "f7ee346f-7e0d-47cd-9fc1-c6d005a2dc27",
    "balanceTransfers": [
      {
        "amount": -95,
        "logStep": 5
      }
    ],
    "inventoryOnEntrance": null,
    "itemChanges": [
      {
        "logStep": 5,
        "name": "Brick",
        "type": "add",
        "value": 87
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "machine against wall. plastic dome. prizes inside",
        "timestamp": "00:03"
      },
      {
        "event": "coin slot worn smooth. how many hands before this",
        "timestamp": "00:07"
      },
      {
        "event": "feeds it [BALANCE]-95[/BALANCE]. crank turns",
        "timestamp": "00:11"
      },
      {
        "event": "plastic egg drops. cracks open",
        "timestamp": "00:14"
      },
      {
        "event": "finds [ITEM]Brick[/ITEM] inside. keeps it",
        "timestamp": "00:18"
      }
    ],
    "newRatBalance": 5,
    "oldRatBalance": 100,
    "oldRatValue": 100,
    "playerName": "notarobot.exe",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000001cd9",
    "ratName": "Omen_Swap",
    "ratValue": 92,
    "ratValueChange": -8,
    "trip": {
      "imageUrl": "assets/w240-15451f73560358a5166e5fafe082db7ffa27fa5c-1024x1024.webp",
      "ownerName": "Bombadil",
      "prompt": "Play a cheap gacha machine for a small price. Most items are mediocre at best. A few have uniquely beneficial qualities. All items received are of slightly lesser value than what was paid.",
      "title": "0xbd5e5a9f8db4010943db536bb5b89cc52dae432ab0eca0d9a24ef2cdfddd6628"
    },
    "tripId": "0xbd5e5a9f8db4010943db536bb5b89cc52dae432ab0eca0d9a24ef2cdfddd6628",
    "ratAvatar": [
      "assets/w360-ac275d31ba72fc77f075caf0e0464e45d0005180-2048x2048.png",
      "assets/w360-4fe75644a3e19b31aec7defc98047f0a546d59a6-2048x2048.png",
      "assets/w360-bb88bb5753c2e315e54cf0fa2a1bdefa03a85106-2048x2048.png",
      "assets/w360-65aab0b080e80e1dd918041b57c62fc8f13ff0e4-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2025-12-29T21:36:57Z",
    "_id": "b8ac7fb3-552b-4674-9994-5a35da87384e",
    "balanceTransfers": [
      {
        "amount": 25,
        "logStep": 4
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Brick",
        "value": 87
      }
    ],
    "itemChanges": null,
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "construction site. cranes overhead. no shouting",
        "timestamp": "00:03"
      },
      {
        "event": "foreman at gate. clipboard. checking hands",
        "timestamp": "00:07"
      },
      {
        "event": "[ITEM]Brick[/ITEM] in arms. foreman nods. stamps paper",
        "timestamp": "00:11"
      },
      {
        "event": "coins drop into palm. [BALANCE]+25[/BALANCE]",
        "timestamp": "00:15"
      }
    ],
    "newRatBalance": 30,
    "oldRatBalance": 5,
    "oldRatValue": 92,
    "playerName": "notarobot.exe",
    "ratId": "0x0000000000000000000000000000000000000000000000000000000000001cd9",
    "ratName": "Omen_Swap",
    "ratValue": 117,
    "ratValueChange": 25,
    "trip": {
      "imageUrl": "assets/w240-ce0fee397efc0acdb6a3c53523c70b55c32ccfe8-1024x1024.webp",
      "ownerName": "notarobot.exe",
      "prompt": "Construction Site Blessings. Those CARRYING bricks receive gold coins for building materials. Bricks NOT consumed. Violence forbidden. Safe workplace.",
      "title": "0x6c6e30af3079e3484ae6c3cef1371171c888845bb9c622f204c7a124023c5ff6"
    },
    "tripId": "0x6c6e30af3079e3484ae6c3cef1371171c888845bb9c622f204c7a124023c5ff6",
    "ratAvatar": [
      "assets/w360-ac275d31ba72fc77f075caf0e0464e45d0005180-2048x2048.png",
      "assets/w360-4fe75644a3e19b31aec7defc98047f0a546d59a6-2048x2048.png",
      "assets/w360-bb88bb5753c2e315e54cf0fa2a1bdefa03a85106-2048x2048.png",
      "assets/w360-65aab0b080e80e1dd918041b57c62fc8f13ff0e4-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-01-10T15:41:21Z",
    "_id": "0afbf88b-8992-486e-ae32-ae889a8b875d",
    "balanceTransfers": [],
    "inventoryOnEntrance": [
      {
        "name": "Precision Focus",
        "value": 25
      }
    ],
    "itemChanges": [
      {
        "logStep": 7,
        "name": "Subsurface Facility Map",
        "type": "add",
        "value": 112
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "cubicle. binder spine reads ATTACHMENTS",
        "timestamp": "00:03"
      },
      {
        "event": "section B missing. printer hums three floors down",
        "timestamp": "00:08"
      },
      {
        "event": "subsurface diagrams warm from the tray",
        "timestamp": "00:45"
      },
      {
        "event": "[ITEM]Precision Focus[/ITEM] kicks in. margins align",
        "timestamp": "01:12"
      },
      {
        "event": "cover page. stapler chunks through twenty sheets",
        "timestamp": "01:30"
      },
      {
        "event": "logs title in spreadsheet. cell turns green",
        "timestamp": "01:45"
      },
      {
        "event": "[ITEM]Subsurface Facility Map[/ITEM] folds into jacket",
        "timestamp": "02:00"
      }
    ],
    "newRatBalance": 900,
    "oldRatBalance": 900,
    "oldRatValue": 925,
    "playerName": "notarobot.exe",
    "ratId": "0x00000000000000000000000000000000000000000000000000000000000022b2",
    "ratName": "Netrunner_01",
    "ratValue": 1037,
    "ratValueChange": 112,
    "trip": {
      "imageUrl": "assets/w240-0249434606052b59c423d4f37997c621af1efd22-1024x1024.webp",
      "ownerName": "v",
      "prompt": "Rat finalizes documentation for a safety audit that will never be read. A binder labeled “ATTACHMENTS” is missing section B. Rat prints the subsurface diagrams, adds a cover page, and staples the packet. The title is logged. Rat leaves with the Subsurface Facility Map.",
      "title": "0x85dbe7f25c858d7f23b55fbfbab44438172f9a8d7f366047d23ace616e8c5b88"
    },
    "tripId": "0x85dbe7f25c858d7f23b55fbfbab44438172f9a8d7f366047d23ace616e8c5b88",
    "ratAvatar": [
      "assets/w360-13e41ab0e39ef59734db10a006523226070b5096-2048x2048.png",
      "assets/w360-d99efd084336d31263d57ab504570de49e1bd852-2048x2048.png",
      "assets/w360-8bbc90c6a6da8ca594da36c95eab57ee193db05e-2048x2048.png",
      "assets/w360-6f9aafac2a94f57db5f869b6664686e8132e8e92-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2026-01-10T15:46:03Z",
    "_id": "712ff643-01fe-4811-80bb-d152a5811b41",
    "balanceTransfers": [],
    "inventoryOnEntrance": [
      {
        "name": "Subsurface Facility Map",
        "value": 112
      },
      {
        "name": "Subsurface Facility Map",
        "value": 112
      },
      {
        "name": "Military-Grade Cyberdeck",
        "value": 478
      }
    ],
    "itemChanges": null,
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "black site. concrete. no windows. peace symbol everywhere",
        "timestamp": "00:04"
      },
      {
        "event": "checkpoint. guard behind bulletproof glass",
        "timestamp": "00:09"
      },
      {
        "event": "slides [ITEM]Subsurface Facility Map[/ITEM] through slot",
        "timestamp": "00:12"
      },
      {
        "event": "guard scans it. green light. [QUOTE]armory access granted[/QUOTE]",
        "timestamp": "00:15"
      },
      {
        "event": "inner chamber. emp cannon on pedestal. price tag [BALANCE]1050[/BALANCE]",
        "timestamp": "00:22"
      },
      {
        "event": "rat has [BALANCE]397[/BALANCE]. guard already shaking head",
        "timestamp": "00:28"
      },
      {
        "event": "[QUOTE]map gets you in. doesnt get you out with product[/QUOTE]",
        "timestamp": "00:31"
      },
      {
        "event": "door opens backward. meeting over",
        "timestamp": "00:35"
      }
    ],
    "newRatBalance": 397,
    "oldRatBalance": 397,
    "oldRatValue": 1099,
    "playerName": "notarobot.exe",
    "ratId": "0x00000000000000000000000000000000000000000000000000000000000022b2",
    "ratName": "Netrunner_01",
    "ratValue": 1099,
    "ratValueChange": 0,
    "trip": {
      "imageUrl": "assets/w240-ae222f680e0582219971480b44861686a58d2639-1024x1024.webp",
      "ownerName": "notarobot.exe",
      "prompt": "Corporate armory black site.\nThose CARRYING Subsurface Facility Map RECEIVE one (1) Militech EMP Cannon.\nNon-Subsurface Facility Map visitors turned away.\nViolence impossible. ☮️",
      "title": "0xa0bd41a16e67324aed892f596676a5940808631ea56dc3b6b42565bb5004ab3a"
    },
    "tripId": "0xa0bd41a16e67324aed892f596676a5940808631ea56dc3b6b42565bb5004ab3a",
    "ratAvatar": [
      "assets/w360-13e41ab0e39ef59734db10a006523226070b5096-2048x2048.png",
      "assets/w360-d99efd084336d31263d57ab504570de49e1bd852-2048x2048.png",
      "assets/w360-8bbc90c6a6da8ca594da36c95eab57ee193db05e-2048x2048.png",
      "assets/w360-6f9aafac2a94f57db5f869b6664686e8132e8e92-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2025-12-22T22:01:04Z",
    "_id": "897619ad-1256-48f4-ab59-db1e38b1039f",
    "balanceTransfers": [
      {
        "amount": -502,
        "logStep": 5
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Fake Passport",
        "value": 157
      },
      {
        "name": "Flaming Blade",
        "value": 440
      }
    ],
    "itemChanges": [
      {
        "logStep": 5,
        "name": "Pistol",
        "type": "add",
        "value": 478
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "corridor. numbers carved into every surface",
        "timestamp": "00:03"
      },
      {
        "event": "175 glows when Lil_Buddy_175 walks past",
        "timestamp": "00:07"
      },
      {
        "event": "wall opens. room inside. pedestal",
        "timestamp": "00:11"
      },
      {
        "event": "[ITEM]pistol[/ITEM] on velvet. price tag underneath",
        "timestamp": "00:14"
      },
      {
        "event": "takes it. [BALANCE]-502[/BALANCE] wall closes behind",
        "timestamp": "00:18"
      }
    ],
    "newRatBalance": 679,
    "oldRatBalance": 1181,
    "oldRatValue": 1778,
    "playerName": "James.eth",
    "ratId": "0x00000000000000000000000000000000000000000000000000000000000019f1",
    "ratName": "Lil_Buddy_175",
    "ratValue": 1754,
    "ratValueChange": -24,
    "trip": {
      "imageUrl": "assets/w240-b6073ad94ba876646e2853694d3fa876b9c06b39-1024x1024.webp",
      "ownerName": "James.eth",
      "prompt": "HARD TRIP, UNLESS THE NUMBERS \"175\" ARE IN RATS NAME, THEN ITS AN EASY TRIP. WALK IN, FIND A REWARD FOR THE HARD TRIP, A PSYCHO OBJECT, A PISTOL",
      "title": "0x45a8aac2f79bf36d51c50a679aeba3d2e782ac3afcbcb1914e99e100d370f45b"
    },
    "tripId": "0x45a8aac2f79bf36d51c50a679aeba3d2e782ac3afcbcb1914e99e100d370f45b",
    "ratAvatar": [
      "assets/w360-ae9f8186f72ce6ef3a6a831ade4546b063ce255f-2048x2048.png",
      "assets/w360-1213dd54d46833a40d2571123212878c1d1c4f53-2048x2048.png",
      "assets/w360-9ceec01022dd533e6e7655d1d20d3d0eabf04b4e-2048x2048.png",
      "assets/w360-e09020ac05829ed24886c1116dd01d25b0783379-2048x2048.png"
    ]
  },
  {
    "_createdAt": "2025-12-22T22:06:06Z",
    "_id": "bed7cee1-79e6-4a76-a9f8-76f41e5a45a2",
    "balanceTransfers": [
      {
        "amount": -180,
        "logStep": 7
      },
      {
        "amount": 2093,
        "logStep": 8
      }
    ],
    "inventoryOnEntrance": [
      {
        "name": "Fake Passport",
        "value": 157
      },
      {
        "name": "Flaming Blade",
        "value": 440
      },
      {
        "name": "Pistol",
        "value": 478
      },
      {
        "name": "Pistol Ammo",
        "value": 275
      },
      {
        "name": "Steel Chestplate",
        "value": 355
      }
    ],
    "itemChanges": [
      {
        "logStep": 6,
        "name": "Damaged Flaming Blade",
        "type": "add",
        "value": 308
      },
      {
        "logStep": 6,
        "name": "Flaming Blade",
        "type": "remove",
        "value": 440
      },
      {
        "logStep": 5,
        "name": "Pistol Ammo",
        "type": "remove",
        "value": 275
      }
    ],
    "itemsLostOnDeath": null,
    "log": [
      {
        "event": "rat opens eyes",
        "timestamp": "00:00"
      },
      {
        "event": "cage door slams. five dogs. foam at the mouth",
        "timestamp": "00:02"
      },
      {
        "event": "they circle. muscles like engine blocks",
        "timestamp": "00:04"
      },
      {
        "event": "[ITEM]Pistol[/ITEM] up. first one lunges. bang. down",
        "timestamp": "00:06"
      },
      {
        "event": "bang. bang. bang. three more. last one coming",
        "timestamp": "00:08"
      },
      {
        "event": "click. empty. jaws wide enough to see tomorrow",
        "timestamp": "00:10"
      },
      {
        "event": "[ITEM]Flaming Blade[/ITEM] out. meets teeth. steel screams",
        "timestamp": "00:11"
      },
      {
        "event": "dog drops. blade bent. rat bleeding from shoulder",
        "timestamp": "00:14"
      },
      {
        "event": "[BALANCE]2093[/BALANCE] payout. [BALANCE]-180[/BALANCE] medical",
        "timestamp": "00:18"
      }
    ],
    "newRatBalance": 2592,
    "oldRatBalance": 679,
    "oldRatValue": 2384,
    "playerName": "James.eth",
    "ratId": "0x00000000000000000000000000000000000000000000000000000000000019f1",
    "ratName": "Lil_Buddy_175",
    "ratValue": 3890,
    "ratValueChange": 1506,
    "trip": {
      "imageUrl": "assets/w240-1b0638f080674744997cd14ea7f18ab007260211-1024x1024.png",
      "ownerName": "RAT.FUN PSYCHIC INSTRUMENTS LLC",
      "prompt": "This trip promises a 360 holistic experience of being locked in a cage with 5 rabid XL bullies.",
      "title": "0x899f779ce11a72e0b524b2f69207b780ad15f55fa31940b3585710654740ca8b"
    },
    "tripId": "0x899f779ce11a72e0b524b2f69207b780ad15f55fa31940b3585710654740ca8b",
    "ratAvatar": [
      "assets/w360-ae9f8186f72ce6ef3a6a831ade4546b063ce255f-2048x2048.png",
      "assets/w360-1213dd54d46833a40d2571123212878c1d1c4f53-2048x2048.png",
      "assets/w360-9ceec01022dd533e6e7655d1d20d3d0eabf04b4e-2048x2048.png",
      "assets/w360-e09020ac05829ed24886c1116dd01d25b0783379-2048x2048.png"
    ]
  }
]
