import { CURRENCY_SYMBOL } from "$lib/modules/ui/constants"

const stringsData = {
  "en-US": {
    address: "Address",
    admin: "Cashboard",
    action: "Action",
    all: "All",
    activeProfit: "Active profit",
    adminUnlocked: "Admin unlocked",
    adminUnlockedMessage: "You unlocked the cashboard",
    alive: "Alive",
    active: "Active",
    activeTrips: "Active trips",
    allowance: "Allowance",
    approveAllowance: "Approve max allowance",
    approveAllowanceInstruction: "Allow the contract to spend on your behalf",
    approvingAllowance: "Approving allowance",
    authorFullTitle: "Moving Castles GmbH",
    balance: "Balance",
    blockNumber: "BlockNumber",
    bottomMarqueeText: "THERE ARE NOT BAD TRIPS, ONLY BAD RATS.",
    buyRat: "Buy Rat",
    buySomeTokens: `Buy some slopamine (${CURRENCY_SYMBOL})`,
    buyTokens: (amount: number): string =>
      `Buy ${amount} Slopamine ({CURRENCY_SYMBOL}) for 0.001ETH`,
    cancel: "Abort",
    causeOfDeathShort: "CoD",
    confirm: "Confirm",
    confirmLiquidationMessage: (name: string): string =>
      `Are you sure you want to liquidate ${name}?`,
    connectedWallet: "Connected wallet",
    creationBlock: "Create @",
    creationCost: "Creation Cost",
    createTrip: "Create Trip",
    creator: "Creator",
    currentRat: "Current Rat",
    debug: "Debug",
    disconnectWallet: "Disconnect wallet",
    empty: "Empty",
    events: "Events",
    environment: "Environment",
    erc20Balance: "ERC20 Balance",
    forceRatLiquidation: "Force liquidate rat",
    getFreeTokens: (amount: number): string => `Get ${amount} free slopamine (${CURRENCY_SYMBOL})`,
    gettingRat: "Getting your rat...",
    gettingTokens: "Getting tokens",
    getTokens: (amount: number): string => `Get ${amount} $RAT`,
    graph: "Graph",
    hasTokens: "Has tokens",
    home: "Home",
    inventory: "Inventory",
    killInProgress: "KILLING IN PROGRESS",
    kills: "Kills",
    lastVisit: "Last Visit",
    liquidate: "Liquidate",
    log: "Log",
    liquidateRatButtonText: "Liquidate Rat",
    liquidateRatInstruction: "Liquidate rat to get the value added to your wallet",
    liquidationBlockShort: "Liq. @",
    liquidationValueShort: "Liq. Val.",
    loadingMsg: "LoadingMsg",
    loadingPercentage: "Loading%",
    masterKey: "Cashboard unlocked",
    maxValuePerWin: "Max value per win",
    minRatValueToEnter: "Min rat value to enter",
    minRatValueWarning: (value: number): string => `Rat value too low (at least ${value})`,
    name: "Name",
    newIndication: "Is new",
    invested: "Invested",
    noRatWarning: "Buy a rat to access this trip",
    noData: "No data",
    onChainBalance: "On-chain Balance",
    owner: "Owner",
    pastRatsCount: "Past Rats",
    player: "Player",
    past: "Past",
    pastTrips: "Past trips",
    profit: "Profit",
    portfolio: "Portfolio",
    rat: "Rat",
    ratAmountKilled: "Rats killed",
    ratCreationTimeout: "Timeout waiting for rat creation",
    rats: "Rats",
    ratValue: "Rat value",
    readyQuestion: "Ready?",
    requestTokens: "Request tokens from the contract",
    revokeApproval: "Revoke approval",
    revokeApprovalInstruction: "Revoke contract spending approval (set to 0)",
    sendRatToTrip: "Send rat to trip",
    spawn: "Spawn",
    spawned: "Spawned",
    stop: "Stop",
    tokens: "Tokens",
    tokensAvailable: "This is available tokens in your wallet",
    topBarMarqueeText: "THERE IS NO LUCK. ONLY SKILL. THERE ARE NO BAD TRIPS, ONLY BAD RATS.",
    topMarqueeText: "RAT.FUN IS A GAME OF SKILL.",
    trip: "Trip",
    trips: "Trips",
    unlockAdminInstruction: "Unlock cashboard",
    visits: "Visits",
    waitForTokens: "You do not have $RAT tokens. Come back later...",
    waitBlocks: (blocks: number): string => `Wait ${blocks} blocks`,
    walletType: "Wallet Type",
    worldAddress: "World address",
    you: "You",
    youIndication: (name: string) => `This is you: ${name}`
  }
} as const

type Locale = keyof typeof stringsData
type Strings = (typeof stringsData)[Locale]

let locale: Locale = "en-US"

export const strings: Strings = stringsData[locale]
