// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityType } from "./tables/EntityType.sol";
import { Brain, BrainData } from "./tables/Brain.sol";
import { Counter } from "./tables/Counter.sol";
