// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData } from "./tables/GameConfig.sol";
import { Name } from "./tables/Name.sol";
import { EntityType } from "./tables/EntityType.sol";
import { Health } from "./tables/Health.sol";
import { Level } from "./tables/Level.sol";
import { Traits } from "./tables/Traits.sol";
import { Dead } from "./tables/Dead.sol";
import { Balance } from "./tables/Balance.sol";
import { OwnedRat } from "./tables/OwnedRat.sol";
import { Owner } from "./tables/Owner.sol";
import { RoomPrompt } from "./tables/RoomPrompt.sol";
import { RoomIndex } from "./tables/RoomIndex.sol";
