// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPlayerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPlayerSystem {
  function ratroom__spawn() external returns (bytes32 playerId);

  function ratroom__addItemToInventory(bytes32 playerId, string memory name) external returns (bytes32 itemId);

  function ratroom__removeItemFromInventory(bytes32 playerId, bytes32 itemId) external;
}
