// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRatSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRatSystem {
  function ratroom__createRat() external returns (bytes32 ratId);

  function ratroom__addTrait(bytes32 _ratId, string memory _name, int256 _value) external returns (bytes32 traitId);

  function ratroom__removeTrait(bytes32 _ratId, bytes32 _traitId) external;

  function ratroom__increaseHealth(bytes32 _ratId, uint256 _change) external;

  function ratroom__decreaseHealth(bytes32 _ratId, uint256 _change) external;

  function ratroom__addItemToLoadOut(bytes32 _itemId) external;

  function ratroom__removeItemFromLoadOut(bytes32 _itemId) external;

  function ratroom__clearLoadOut(bytes32 _ratId, bytes32 _roomId) external;
}
