// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRatSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRatSystem {
  function ratroom__addTrait(bytes32 ratId, string memory name) external returns (bytes32 traitId);

  function ratroom__removeTrait(bytes32 ratId, bytes32 traitId) external;

  function ratroom__changeStat(bytes32 ratId, string memory statName, uint256 change, bool negative) external;
}
