// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRoomSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRoomSystem {
  function ratroom__createRoom(string memory _roomPrompt) external returns (bytes32 roomId);

  function ratroom__changeRoomBalance(bytes32 _roomId, uint256 _change, bool _negative) external;

  function ratroom__transferBalanceToPlayer(bytes32 _roomId, bytes32 _playerId, uint256 _amount) external;
}
